namespace: default #OPTIONAL namespace for resources to be deployed

#Cluster Issuer Resource
email: example@gmail.com                                              #OPTIONAL
externalAccountBinding:                                               #OPTIONAL
  keyID:                                                              #REQUIRED if using external account binding
  secretKey:                                                          #REQUIRED if using external account binding
preferredChain: "ISRG Root X1"                                        #OPTIONAL
acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory #REQUIRED, Example of ACME Server URL 
hostedZoneID:                                                         #OPTIONAL
region: global                                                        #REQUIRED
dnsZones:                                                             #OPTIONAL, List of dns zones
  - domain.name

#Certificate Resource
commonName: example.com       #REQUIRED
isCA: true                    #OPTIONAL
 
certManager:
  enabled: false
