{{- if .Values.externalAccountBinding.secretKey }}
{{- with .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-acme-server-secretkey
  namespace: {{ .namespace | quote }}
stringData:
  secret: {{ .externalAccountBinding.secretKey | quote }}
{{- end }}
{{- end }}