{{- with .Values }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ $.Release.Name }}-route53-clusterissuer"
  namespace: {{ .namespace | quote }}
spec:
  acme:
    {{- if .email }}
    email: {{ .email | quote }}
    {{- end }}
    {{- if .preferredChain }}
    preferredChain: {{ .preferredChain | quote }}
    {{- end }}
    {{- if .externalAccountBinding.keyID }}
    externalAccountBinding:
      keyID: {{ .externalAccountBinding.keyID | quote }}
      keySecretRef:
        key: secret
        name: {{ $.Release.Name }}-acme-server-secretkey
    {{- end }}
    privateKeySecretRef:
      name: "{{ $.Release.Name }}-route53-secretkeyref"
    server: {{ .acmeServerUrl | quote }}
    solvers:
    - dns01:
    {{- if and (not .azureDNS.enabled) .route53.enabled }}
      {{- with .route53 }}
        route53:
          {{- if .hostedZoneID }}
          hostedZoneID: {{ .hostedZoneID | quote }}
          {{- end }}
          region: {{ .region | default "global" | quote }}
      {{- if $.Values.dnsZones }}
      selector:
        dnsZones:
        {{- $.Values.dnsZones | toYaml | nindent 12 }}
      {{- end }}
      {{- end }}
    {{- else if and (not .route53.enabled) .azureDNS.enabled }}
      {{- with .azureDNS }}
        azureDNS:
          clientID: {{ .clientID | quote }}
          {{- if and .clientSecretSecretRef.name .clientSecretSecretRef.key }}
          clientSecretSecretRef:
            name: {{ .clientSecretSecretRef.name | quote }}
            key: {{ .clientSecretSecretRef.key | quote }}
          {{- end }}
          subscriptionID: {{- .subscriptionID | quote }}
          tenantID: {{- .tenantID | quote }}
          resourceGroupName: {{- .resourceGroupName | quote}}
          hostedZoneName: {{- .hostedZoneName | quote }}
          environment: {{- .environment | quote }}
      {{- end}}
    {{- end }}
{{- end }}