{{- with .Values }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ $.Release.Name }}-route53-clusterissuer"
  namespace: {{ .namespace | quote }}
spec:
  acme:
    {{- if .email }}
    email: {{ .email | quote }}
    {{- end }}
    {{- if .preferredChain }}
    preferredChain: {{ .preferredChain | quote }}
    {{- end }}
    {{- if .externalAccountBinding.keyID }}
    externalAccountBinding:
      keyID: {{ .externalAccountBinding.keyID | quote }}
      keySecretRef:
        key: secret
        name: {{ $.Release.Name }}-acme-server-secretkey
    {{- end }}
    privateKeySecretRef:
      name: "{{ $.Release.Name }}-route53-secretkeyref"
    server: {{ .acmeServerUrl | quote }}
    solvers:
    - dns01:
        route53:
          {{- if .hostedZoneID }}
          hostedZoneID: {{ .hostedZoneID | quote }}
          {{- end }}
          region: {{ .region | default "global" | quote }}
      {{- if .dnsZones }}
      selector:
        dnsZones:
        {{- .dnsZones | toYaml | nindent 12 }}
      {{- end }}
{{- end }}