name: Update dependency version

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  check_updates:
    name: Check dependency version 
    
    runs-on: 
      - ubuntu-latest
      
    outputs:
      version: ${{ steps.actual_version.outputs.package }}
    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup yq
        uses: dcarbone/install-yq-action@v1.1.0
        with:
          version: 'v4.30.6'
          download-compressed: 'true'
          force: 'false'
          
      - name: Setup jq
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '1.6'
          force: 'false'
        
      - name: Current version
        id: current_version
        run: echo "dependency=$(cat Chart.yaml | yq .dependencies[0].version)" >> $GITHUB_OUTPUT
        
      - name: Actual version
        id: actual_version
        run: echo "package=$(curl https://artifacthub.io/api/v1/packages/helm/cert-manager/cert-manager | jq .version)" >> $GITHUB_OUTPUT
        
      - name: Check for new version
        if: contains(steps.actual_version.outputs.package, steps.current_version.outputs.dependency)
        run: exit 1
  
  update_package:
    name: Update dependency
    if: success()  
    needs: 
      - check_updates
    
    runs-on: 
      - ubuntu-latest
    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: main
    
      - name: Setup yq
        uses: dcarbone/install-yq-action@v1.1.0
        with:
          version: 'v4.30.6'
          download-compressed: 'true'
          force: 'false'
    
      - name: Change dep version
        run: yq e -i '.dependencies[0].version = ${{ needs.check_updates.outputs.version }}' Chart.yaml
        
      - uses: azure/setup-helm@v3
        with:
           version: latest
           token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update helm dependency
        run: helm dep up

      - name: Push changes
        uses: actions-x/commit@v6
        with:
          email: hakob.mkoyan771@gmail.com
          name: Dependency version update
          branch: main
          files: .
          repository: https://github.com/infraheads/cert-manager-blueprints
          token: ${{ secrets.TOKEN }}
          force: true
          directory: .
